spring.application.name=springsecurity
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/icast
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.type=org.